language: en

pipeline:
  - name: SpacyNLP
    model: "en_core_web_sm"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: RegexEntityExtractor
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.4               
    ambiguity_threshold: 0.1     



policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_action_name: "action_default_fallback"
  core_fallback_threshold: 0.3
  enable_fallback_prediction: True
- name: TEDPolicy
  max_history: 5
  epochs: 100
  
assistant_id: 20250608-234450-proper-digraph
